---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees: 
      - "MattKobayashi"
    commit-message:
      prefix: "fix(deps)"
  - package-ecosystem: "docker"
    directory: "**/*"
    schedule:
      interval: "daily"
    assignees: 
      - "MattKobayashi"
    commit-message:
      prefix: "fix(deps)"
  - package-ecosystem: "pip"
    directory: "**/*"
    schedule:
      interval: "daily"
    assignees: 
      - "MattKobayashi"
    commit-message:
      prefix: "fix(deps)"
